# -*- coding: utf-8 -*-
"""Loan Approval.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jyyhkY2r1jRIrG6aGlhncfRBv0oHSPnE

**Decision Tree** -> It is a binary tree with conditions and decisions . for every input it recursively find the decisions and gives out the best output

importing necessary packages
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("loan_data.csv")

data

X=data.drop("Loan_Status",axis=1)
y=data["Loan_Status"]

X,y

encoder=LabelEncoder()

for column in X.columns:
  X[column] = encoder.fit_transform(X[column])

X

y=encoder.fit_transform(y)

y

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model = DecisionTreeClassifier(
    criterion="gini",
    max_depth=5,

)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

accuracy=accuracy_score(y_test,y_pred)
accuracy

input_data = {
    'Gender': 'Male',
    'Married': 'Yes',
    'Education': 'Graduate',
    'Self_Employed': 'No',
    'ApplicantIncome': 50000,
    'CoapplicantIncome': 150000,
    'LoanAmount': 160,
    'Loan_Amount_Term': 3600,
    'Credit_History': 8,
    'Property_Area': 'Urban'
}

# Create a dictionary to store LabelEncoders for each categorical column.
# We need to re-fit them based on the original 'data' DataFrame to ensure consistency,
# as the 'encoder' object was overwritten during X's transformation.
column_encoders = {}
categorical_cols = ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area']

for col in categorical_cols:
    le = LabelEncoder()
    # Fit the encoder on the unique values of the original data's column
    le.fit(data[col])
    column_encoders[col] = le

encoded_input_values = []

for column in X.columns:
    value = input_data[column]
    if column in column_encoders: # Check if we have a specific encoder for this column
        # Use the stored encoder to transform the input value
        value = column_encoders[column].transform([value])[0]
    # For numerical columns, 'value' remains as is from input_data
    encoded_input_values.append(value)

encoded_input = np.array(encoded_input_values).reshape(1, -1)

prediction = model.predict(encoded_input)

print("Loan Approved" if prediction[0] == 1 else "Loan Rejected")

